---
abstract: 'helper for processing multiple text files in a stream (through a pipe, usually)'
author:
  - 'Thomas Orgis <thomas@orgis.org>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.39
dynamic_config: 1
generated_by: 'Module::Build version 0.3901, CPAN::Meta::Converter version 2.120630'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Text-ASCIIPipe
provides:
  Text::ASCIIPipe:
    file: lib/Text/ASCIIPipe.pm
    version: 1.000001
requires:
  perl: 5.006
resources:
  license: http://dev.perl.org/licenses/
version: 1.000001
